#######################################################################
# Create an Ubuntu LINUX environment with tools and dependencies for building the EMOD binaries
#
# This Docker build file is provided as a convenience for building the EMOD binaries on LINUX.
#######################################################################
FROM ubuntu:26.04

ENV DEBIAN_FRONTEND=noninteractive
ENV USER=EMOD_USER

RUN apt-get update

RUN apt-get install -y git
RUN apt-get install -y g++
RUN apt-get install -y libc-dev
RUN apt-get install -y python3-dev
RUN apt-get install -y libmpich-dev
RUN apt-get install -y libboost-dev
RUN apt-get install -y scons

RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/*
