name: Build Docker Images

on:
  # Allows manual run from the Actions tab
  workflow_dispatch:
    inputs:
      os_name:
        description: 'Container OS'
        required: true
        default: 'Ubuntu'
        type: choice
        options:
          - 'Ubuntu'
      type:
        description: 'Container type'
        required: true
        default: 'buildenv'
        type: choice
        options:
          - 'buildenv'
          - 'testenv'
          - 'runtime'
      version_tag:
        description: 'Version tag'
        required: true
        type: string
        default: 'latest'

env:
  REGISTRY: ghcr.io
  ORG_NAME: emod-hub  # Must be lowercase

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    env:
      dfile_name: ${{ format('Dockerfile.{0}.{1}', inputs.type, inputs.os_name) }}
      image_name: ${{ format('emod-{0}-{1}', inputs.os_name, inputs.type) }}
    permissions:
      artifact-metadata: write
      attestations: write
      id-token: write
      packages: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ inputs.os_name}}/${{ env.dfile_name }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.ORG_NAME }}/${{ env.image_name }}:${{ inputs.version_tag }}
      - name: Generate artifact attestation
        uses: actions/attest@v4
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.ORG_NAME }}/${{ env.image_name }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
